-- MySQL Script generated by MySQL Workbench
-- Fri May 13 10:49:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oocinema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oocinema` ;

-- -----------------------------------------------------
-- Schema oocinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oocinema` DEFAULT CHARACTER SET utf8 ;
USE `oocinema` ;

-- -----------------------------------------------------
-- Table `oocinema`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oocinema`.`film` (
  `id` INT NOT NULL,
  `titolo` VARCHAR(45) NULL,
  `descrizione` LONGTEXT NULL,
  `genere` VARCHAR(45) NULL,
  `durata` INT NULL,
  `regista` VARCHAR(45) NULL,
  `cast` VARCHAR(45) NULL,
  `coverPath` LONGTEXT NULL,
  `trailerPath` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oocinema`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oocinema`.`sala` (
  `id` INT NOT NULL,
  `n_righe` INT NULL,
  `n_col` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oocinema`.`proiezione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oocinema`.`proiezione` (
  `id` INT NOT NULL,
  `prezzo` FLOAT NOT NULL,
  `film_id` INT NOT NULL,
  `sala_id` INT NOT NULL,
  `giorno` VARCHAR(45) NULL,
  `orario` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proiezioni_film_idx` (`film_id` ASC) VISIBLE,
  INDEX `fk_proiezione_sala1_idx` (`sala_id` ASC) VISIBLE,
  CONSTRAINT `fk_proiezioni_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `oocinema`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proiezione_sala1`
    FOREIGN KEY (`sala_id`)
    REFERENCES `oocinema`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oocinema`.`acquirente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oocinema`.`acquirente` (
  `user` VARCHAR(45) NOT NULL,
  `psw` VARCHAR(45) NOT NULL,
  `tipo` INT(1) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `compleanno` VARCHAR(45) NULL,
  PRIMARY KEY (`user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oocinema`.`prenotazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oocinema`.`prenotazione` (
  `id` INT NOT NULL,
  `data_acquisto` VARCHAR(45) NULL,
  `n_posti` INT NULL,
  `proiezione_id` INT NOT NULL,
  `acquirente_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prenotazione_proiezione1_idx` (`proiezione_id` ASC) VISIBLE,
  INDEX `fk_prenotazione_acquirente1_idx` (`acquirente_user` ASC) VISIBLE,
  CONSTRAINT `fk_prenotazione_proiezione1`
    FOREIGN KEY (`proiezione_id`)
    REFERENCES `oocinema`.`proiezione` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prenotazione_acquirente1`
    FOREIGN KEY (`acquirente_user`)
    REFERENCES `oocinema`.`acquirente` (`user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oocinema`.`cinema_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oocinema`.`cinema_info` (
  `nome` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `user` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `indirizzo` VARCHAR(45) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oocinema`.`ora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oocinema`.`ora` (
  `ora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oocinema`.`posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oocinema`.`posto` (
  `riga` INT NOT NULL,
  `colonna` INT NOT NULL,
  `prenotazione_id` INT NOT NULL,
  PRIMARY KEY (`colonna`, `riga`),
  INDEX `fk_posto_prenotazione1_idx` (`prenotazione_id` ASC) VISIBLE,
  CONSTRAINT `fk_posto_prenotazione1`
    FOREIGN KEY (`prenotazione_id`)
    REFERENCES `oocinema`.`prenotazione` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
